name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          chmod -R +x node_modules/.bin/
          npm run build

      - name: Deploy to gh-pages
        run: |
          cd dist
          git init
          git config user.email "deploy@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/choccymilkboi/Lang-Podcast.git HEAD:gh-pages